### PR TITLE
Use found PYGTAIL instead of static LOGTAIL in zabbix_postfix.sh

### PR DESCRIPTION
**Pull request by abruening-iwt**
The script currently tries to find pygtail in various paths but then never uses it, instead always trying LOGTAIL

### CODE REVIEW

**Comment by rafael747** [comment]
hello @abruening-iwt 
After your changes `${PYGTAIL}` will be unset
And the `${LOGTAIL}` is always pointing to the provided `pygtail.py` script
Or am I missing something here?

**Comment by abruening-iwt** [comment]
Hi, it's the other way around, LOGTAIL is static in the current version an PYGTAIL is never used, my PR removes LOGTAIL and makes the script use PYGTAIL.

**Comment by rafael747** [comment]
the `$LOGTAIL` variable is pointing to the provided `pygtail.py`
the `$PYGTAIL` variable is never defined (in this repo, at least)
if I understood correctly, your suggestion is to use "any" pygtail.py found in PATH
but for this you would need to change line 37 from `${LOGTAIL}` to `pygtail.py`
is that right?

**Comment by abruening-iwt** [comment]
That's correct, I assumed that was the reason for looking for PYGTAIL in lines 12 to 21.

Maybe it would be better to look for /usr/local/sbin/pygtail first, then try the other options and exit with an error in else.

**Comment by rafael747** [comment]
Now I got it, I was totally missing the lines from 12 to 21 😅 
This way it is missing just one thing IMO
in line 20:
`PYGTAIL=/usr/local/sbin/pygtail` -> `PYGTAIL=/usr/local/sbin/pygtail.py`

**Comment by abruening-iwt** [comment]
Oh yeah, I must've missed that.

**Comment by rafael747** [comment]
@abruening-iwt 
can you add make the proposed changes in your branch?
then I can merge this PR

**Comment by abruening-iwt** [comment]
Done

**Pull request merged**
